export const TypographyVariants = (headingFont: string) => ({
  display1: {
    fontFamily: headingFont,
    fontSize: "52px",
    lineHeight: "120%",
    fontWeight: 600,
  },
  display2: {
    fontFamily: headingFont,
    fontSize: "42px",
    lineHeight: "120%",
    fontWeight: 600,
  },
  display3: {
    fontFamily: headingFont,
    fontSize: "34px",
    lineHeight: "120%",
    fontWeight: 600,
  },
  h1: {
    fontFamily: headingFont,
    fontSize: "28px",
    lineHeight: "120%",
    fontWeight: 700,
  },
  h2: {
    fontFamily: headingFont,
    fontSize: "24px",
    lineHeight: "120%",
    fontWeight: 700,
  },
  h3: {
    fontFamily: headingFont,
    fontSize: "20px",
    lineHeight: "120%",
    fontWeight: 700,
  },
  label1: {
    fontSize: "18px",
    lineHeight: "120%",
    fontWeight: 400,
    letterSpacing: "2.7px",
    textTransform: "uppercase",
  },
  label2: {
    fontSize: "16px",
    lineHeight: "120%",
    fontWeight: 400,
    letterSpacing: "2.4px",
    textTransform: "uppercase",
  },
  label3: {
    fontSize: "14px",
    lineHeight: "120%",
    fontWeight: 400,
    letterSpacing: "2.1px",
    textTransform: "uppercase",
  },
  label4: {
    fontSize: "12px",
    lineHeight: "120%",
    fontWeight: 400,
    letterSpacing: "1.8px",
    textTransform: "uppercase",
  },
  singleLine1: {
    fontSize: "18px",
    lineHeight: "100%",
    fontWeight: 400,
    letterSpacing: "0.18px",
  },
  singleLine2: {
    fontSize: "16px",
    lineHeight: "100%",
    fontWeight: 400,
    letterSpacing: "0.16px",
  },
  singleLine3: {
    fontSize: "14px",
    lineHeight: "100%",
    fontWeight: 400,
    letterSpacing: "0.28px",
  },
  singleLine4: {
    fontSize: "12px",
    lineHeight: "100%",
    fontWeight: 400,
    letterSpacing: "0.24px",
  },
  multiLine1: {
    fontSize: "18px",
    lineHeight: "150%",
    fontWeight: 400,
    letterSpacing: "0.18px",
  },
  multiLine2: {
    fontSize: "16px",
    lineHeight: "150%",
    fontWeight: 400,
    letterSpacing: "0.16px",
  },
  multiLine3: {
    fontSize: "14px",
    lineHeight: "150%",
    fontWeight: 400,
    letterSpacing: "0.28px",
  },
  multiLine4: {
    fontSize: "12px",
    lineHeight: "150%",
    fontWeight: 400,
    letterSpacing: "0.24px",
  },
  link1: {
    fontSize: "18px",
    lineHeight: "100%",
    fontWeight: 600,
    cursor: "pointer",
    letterSpacing: "0.18px",
  },
  link2: {
    fontSize: "16px",
    lineHeight: "100%",
    fontWeight: 600,
    cursor: "pointer",
  },
  link3: {
    fontSize: "14px",
    lineHeight: "100%",
    fontWeight: 600,
    cursor: "pointer",
  },
  link4: {
    fontSize: "12px",
    lineHeight: "100%",
    fontWeight: 600,
    cursor: "pointer",
  },
});

export const MuiTypography = {
  MuiTypography: {
    defaultProps: {
      variantMapping: {
        h1: "h1",
        h2: "h2",
        h3: "h3",
        h4: "h4",
        h5: "h5",
        h6: "h6",
        subtitle1: "h6",
        subtitle2: "h6",
        body1: "p",
        body2: "p",
        label1: "p",
        label2: "p",
        label3: "p",
        label4: "p",
        singleLine1: "p",
        singleLine2: "p",
        singleLine3: "p",
        singleLine4: "p",
        multiLine1: "p",
        multiLine2: "p",
        multiLine3: "p",
        multiLine4: "p",
        link1: "p",
        link2: "p",
        link3: "p",
        link4: "p",
        display1: "h1",
        display2: "h2",
        display3: "h3",
      },
    },
  },
};

